// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU0yOlLrGQ0R0sq8QHtM9EeEPrbMfeeow',
    appId: '1:399603907387:web:e1d99e3b1d10f14cb3951e',
    messagingSenderId: '399603907387',
    projectId: 'test-api-cb458',
    authDomain: 'test-api-cb458.firebaseapp.com',
    databaseURL: 'https://test-api-cb458-default-rtdb.firebaseio.com',
    storageBucket: 'test-api-cb458.appspot.com',
    measurementId: 'G-RM311LLJEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBIFSNYl3whrCmYBkejnBW1bKVkA2A7yQ',
    appId: '1:399603907387:android:9e772abfa96333d4b3951e',
    messagingSenderId: '399603907387',
    projectId: 'test-api-cb458',
    databaseURL: 'https://test-api-cb458-default-rtdb.firebaseio.com',
    storageBucket: 'test-api-cb458.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2VkpkhuSQJe6keeoXlBw42a89559mSSs',
    appId: '1:399603907387:ios:7d403ca960e75714b3951e',
    messagingSenderId: '399603907387',
    projectId: 'test-api-cb458',
    databaseURL: 'https://test-api-cb458-default-rtdb.firebaseio.com',
    storageBucket: 'test-api-cb458.appspot.com',
    iosBundleId: 'com.example.applist3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2VkpkhuSQJe6keeoXlBw42a89559mSSs',
    appId: '1:399603907387:ios:7d403ca960e75714b3951e',
    messagingSenderId: '399603907387',
    projectId: 'test-api-cb458',
    databaseURL: 'https://test-api-cb458-default-rtdb.firebaseio.com',
    storageBucket: 'test-api-cb458.appspot.com',
    iosBundleId: 'com.example.applist3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU0yOlLrGQ0R0sq8QHtM9EeEPrbMfeeow',
    appId: '1:399603907387:web:bf116a3a5fc9757bb3951e',
    messagingSenderId: '399603907387',
    projectId: 'test-api-cb458',
    authDomain: 'test-api-cb458.firebaseapp.com',
    databaseURL: 'https://test-api-cb458-default-rtdb.firebaseio.com',
    storageBucket: 'test-api-cb458.appspot.com',
    measurementId: 'G-27Y0D8ERW4',
  );

}